package newstime.fronteira;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import newstime.DAO.AutorDAO;
import newstime.DAO.BancoDados;
import newstime.DAO.EditoraDAO;
import newstime.controle.ControleAdministracao;
import newstime.entidade.Autor;
import newstime.entidade.Editora;
import newstime.excecao.BancoException;

/**
 * Classe do formulário de CRUD do livro
 * @author lukin
 */
public class CadastroLivro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLivro
     */
    private boolean oferta = false, digital = false;//variaveis para radio buton

    public CadastroLivro() {
        initComponents();
        this.setTitle("Cadastro de Livros - Livraria Newstime");
        //Gera os anos
        Date atual = new Date();
        for(int i = (atual.getYear()+1900);i >= 1000;i--)
            cmb_ano.addItem(String.valueOf(i));
        
        //Autor-Editora
        BancoDados db = new BancoDados();
        AutorDAO aDAO = new AutorDAO(db);
        EditoraDAO eDAO = new EditoraDAO(db);
        ArrayList<Autor> listaAutores;
        ArrayList<Editora> listaEditoras;
        try {
            listaAutores = (ArrayList<Autor>) aDAO.listar();
            listaEditoras = (ArrayList<Editora>) eDAO.listar();
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        
        cmb_autor.removeAllItems();
        cmb_autor.addItem("Selecione...");
        
        cmb_editora.removeAllItems();
        cmb_editora.addItem("Selecione...");
        
        for (Autor listaAutore : listaAutores) {
            cmb_autor.addItem(listaAutore);
        }
        for (Editora listaEditora : listaEditoras) {
            cmb_editora.addItem(listaEditora);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_categoria = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_resumo = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_sumario = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        rdo_digitalSim = new javax.swing.JRadioButton();
        rdo_digitalNao = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rdo_ofertSim = new javax.swing.JRadioButton();
        rdo_ofertaNao = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txt_numPaginas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_precoVenda = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_precoOferta = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cmb_ano = new javax.swing.JComboBox<String>();
        txt_qtd = new javax.swing.JFormattedTextField();
        txt_isbn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_precoCusto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cmb_formato = new javax.swing.JComboBox<String>();
        cmb_autor = new javax.swing.JComboBox();
        cmb_editora = new javax.swing.JComboBox();
        txt_margemLucro = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(870, 740));
        setResizable(false);
        setSize(new java.awt.Dimension(870, 740));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setLabelFor(cmb_autor);
        jLabel2.setText("Autor:");
        jLabel2.setToolTipText("Selecione o autor do livro.");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setLabelFor(txt_titulo);
        jLabel3.setText("Título:");
        jLabel3.setToolTipText("Digite o título do livro.");

        txt_titulo.setToolTipText("Digite o título do livro.");
        txt_titulo.setPreferredSize(new java.awt.Dimension(0, 24));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setLabelFor(cmb_editora);
        jLabel4.setText("Editora:");
        jLabel4.setToolTipText("Selecione a editora do livro.");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setLabelFor(cmb_ano);
        jLabel5.setText("Ano de Publicação:");
        jLabel5.setToolTipText("Selecione o ano de publicação do livro.");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setLabelFor(cmb_categoria);
        jLabel7.setText("Categoria:");
        jLabel7.setToolTipText("Selecione a categoria do livro.");

        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..", "ADMINISTRACAO", "AGROPECUARIA", "ARTES", "AUDIOLIVRO", "AUTOAJUDA", "CIENCIAS_BIO", "CIENCIAS_EXA", "CIENCIAS_HUM", "CONTABILIDADE", "IDIOMA", "DICIONARIO", "DIDATICO", "DIREITO", "ECONOMIA", "ENG_TEC", "ESPORTE", "GASTRONOMIA", "GEO_HIST", "INFORMATICA", "LINGUISTICA", "LITER_ESTR", "LITER_INFA", "LITER_NACIO", "MEDICINA", "RELIGIAO", "TURISMO" }));
        cmb_categoria.setToolTipText("Selecione a categoria do livro.");
        cmb_categoria.setPreferredSize(new java.awt.Dimension(0, 24));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setLabelFor(txt_isbn);
        jLabel8.setText("ISBN:");
        jLabel8.setToolTipText("<html> Digite o ISBN do livro.<br/> É por ele que é feito a pesquisa. </html>");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Quantidade:");
        jLabel9.setToolTipText("<html>\nDigite a quantidade de livros.<br/>\nDigite somente números inteiros não negativos.\n</html>");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setLabelFor(txt_resumo);
        jLabel10.setText("Resumo");
        jLabel10.setToolTipText("Escreva o resumo do livro.");

        txt_resumo.setColumns(20);
        txt_resumo.setRows(5);
        txt_resumo.setToolTipText("Escreva o resumo do livro.");
        txt_resumo.setPreferredSize(new java.awt.Dimension(0, 24));
        jScrollPane1.setViewportView(txt_resumo);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setLabelFor(txt_sumario);
        jLabel11.setText("Sumário");
        jLabel11.setToolTipText("Escreva o sumário do livro.");

        txt_sumario.setColumns(20);
        txt_sumario.setRows(5);
        txt_sumario.setToolTipText("Escreva o sumário do livro.");
        txt_sumario.setPreferredSize(new java.awt.Dimension(0, 24));
        jScrollPane2.setViewportView(txt_sumario);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setLabelFor(cmb_formato);
        jLabel12.setText("Formato do livro:");
        jLabel12.setToolTipText("Selecione o formato do livro.");

        buttonGroup1.add(rdo_digitalSim);
        rdo_digitalSim.setText("Sim");
        rdo_digitalSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_digitalSimActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_digitalNao);
        rdo_digitalNao.setSelected(true);
        rdo_digitalNao.setText("Não");
        rdo_digitalNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_digitalNaoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Em Oferta?");
        jLabel13.setToolTipText("<html>\nIndique se o livro estará em oferta.<br/>\nIsso fará com que o preço de oferta seja válido no momento da venda.\n</html>");

        buttonGroup2.add(rdo_ofertSim);
        rdo_ofertSim.setText("Sim");
        rdo_ofertSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ofertSimActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdo_ofertaNao);
        rdo_ofertaNao.setSelected(true);
        rdo_ofertaNao.setText("Não");
        rdo_ofertaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ofertaNaoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("Livro Digital?");
        jLabel14.setToolTipText("Indique se o livro é digital ou não.");

        txt_numPaginas.setToolTipText("<html>\nDigite o número de páginas do livro.<br/>\nDigite somente números inteiros.\n</html>");
        txt_numPaginas.setPreferredSize(new java.awt.Dimension(0, 24));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("Margem de Lucro (%):");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setLabelFor(txt_precoVenda);
        jLabel16.setText("Preço de Venda:");
        jLabel16.setToolTipText("<html> Digite o preço pelo qual o livro será vendido.<br/> Digite somente números positivos. Use \".\" como separador de casa decimal. </html>");

        txt_precoVenda.setToolTipText("<html>\nDigite o preço pelo qual o livro será vendido.<br/>\nDigite somente números positivos. Use \".\" como separador de casa decimal.\n</html>");
        txt_precoVenda.setPreferredSize(new java.awt.Dimension(0, 24));
        txt_precoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precoVendaKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel17.setLabelFor(txt_precoOferta);
        jLabel17.setText("Preço de Oferta:");
        jLabel17.setToolTipText("<html> Digite o preço pelo qual o livro será vendido em oferta.<br/> Digite somente números positivos. Use \".\" como separador de casa decimal. </html>");

        txt_precoOferta.setToolTipText("<html>\nDigite o preço pelo qual o livro será vendido em oferta.<br/>\nDigite somente números positivos. Use \".\" como separador de casa decimal.\n</html>");
        txt_precoOferta.setPreferredSize(new java.awt.Dimension(0, 24));

        btn_pesquisar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.setToolTipText("");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_alterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.setEnabled(false);
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_cadastrar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cmb_ano.setToolTipText("Selecione o ano de publicação do livro.");
        cmb_ano.setAutoscrolls(true);
        cmb_ano.setPreferredSize(new java.awt.Dimension(0, 24));

        txt_qtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txt_qtd.setToolTipText("<html>\nDigite a quantidade de livros.<br/>\nDigite somente números inteiros não negativos.\n</html>");
        txt_qtd.setPreferredSize(new java.awt.Dimension(0, 24));

        txt_isbn.setToolTipText("<html>\nDigite o ISBN do livro.<br/>\nÉ por ele que é feito a pesquisa.\n</html>");
        txt_isbn.setPreferredSize(new java.awt.Dimension(0, 24));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel20.setLabelFor(txt_precoCusto);
        jLabel20.setText("Preço de Custo:");
        jLabel20.setToolTipText("<html> Digite o preço de custo do livro.<br/> Digite somente números positivos. Use \".\" como separador de casa decimal. </html>");

        txt_precoCusto.setToolTipText("<html> Digite o preço de custo do livro.<br/> Digite somente números positivos. Use \".\" como separador de casa decimal. </html>");
        txt_precoCusto.setPreferredSize(new java.awt.Dimension(0, 24));
        txt_precoCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precoCustoKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel21.setLabelFor(txt_numPaginas);
        jLabel21.setText("Número de páginas:");
        jLabel21.setToolTipText("<html> Digite o número de páginas do livro.<br/> Digite somente números inteiros. </html>");

        cmb_formato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..", "BROCHURA", "GRAMPO", "CAPA_DURA", "DIGITAL" }));
        cmb_formato.setToolTipText("Selecione o formato do livro.");
        cmb_formato.setPreferredSize(new java.awt.Dimension(0, 24));

        cmb_autor.setToolTipText("Selecione o autor do livro.");
        cmb_autor.setPreferredSize(new java.awt.Dimension(0, 24));

        cmb_editora.setToolTipText("Selecione a editora do livro.");
        cmb_editora.setPreferredSize(new java.awt.Dimension(0, 24));

        txt_margemLucro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_margemLucro.setEnabled(false);
        txt_margemLucro.setFocusable(false);
        txt_margemLucro.setOpaque(false);
        txt_margemLucro.setPreferredSize(new java.awt.Dimension(64, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_precoVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_precoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_margemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_precoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(126, 126, 126)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdo_digitalSim)
                                            .addComponent(rdo_ofertSim)))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdo_digitalNao)
                                    .addComponent(rdo_ofertaNao)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                                    .addComponent(cmb_autor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_isbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_editora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmb_formato, 0, 233, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmb_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btn_pesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btn_alterar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btn_excluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_precoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_digitalSim)
                    .addComponent(rdo_digitalNao)
                    .addComponent(txt_margemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_precoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_ofertSim)
                    .addComponent(rdo_ofertaNao)
                    .addComponent(txt_precoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_digitalSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_digitalSimActionPerformed
        digital = true;
    }//GEN-LAST:event_rdo_digitalSimActionPerformed

    private void rdo_digitalNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_digitalNaoActionPerformed
        digital = false;
    }//GEN-LAST:event_rdo_digitalNaoActionPerformed

    private void rdo_ofertSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ofertSimActionPerformed
        //System.out.println("Sim");
        oferta = true;
    }//GEN-LAST:event_rdo_ofertSimActionPerformed

    private void rdo_ofertaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ofertaNaoActionPerformed
        //System.out.println("Nao");
        oferta = false;
    }//GEN-LAST:event_rdo_ofertaNaoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        //Verifica os campos
        if ("".equals(txt_isbn.getText()) || "".equals(txt_titulo.getText()) || cmb_autor.getSelectedIndex() == 0 ||
                cmb_editora.getSelectedIndex() == 0 || "Selecione..".equals(cmb_categoria.getSelectedItem().toString()) ||
                "".equals(txt_resumo.getText()) || "".equals(txt_sumario.getText()) || "".equals(txt_qtd.getText()) ) {
            JOptionPane.showMessageDialog(null, "Há campos não preenchidos.");
            return;
        }
        
        //Cadastra
        ControleAdministracao controleAdm = new ControleAdministracao();
        String data = "01" + "01" + cmb_ano.getSelectedItem().toString();
        controleAdm.inserirLivro(txt_isbn.getText(), txt_titulo.getText(), ((Autor)cmb_autor.getSelectedItem()).getID(), ((Editora)cmb_editora.getSelectedItem()).getID(), data, cmb_categoria.getSelectedItem().toString(), txt_resumo.getText(), txt_sumario.getText(),  cmb_formato.getSelectedItem().toString(), txt_numPaginas.getText(), txt_qtd.getText(), txt_precoVenda.getText(), txt_precoOferta.getText(), txt_numPaginas.getText(), oferta, digital);

        limparCampos();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        //Verifica o campo ISBN
        if ( "".equals(txt_isbn.getText()) ) {
            JOptionPane.showMessageDialog(rootPane, "Informe o ISBN para excluir.");
            txt_isbn.requestFocus();
            return;
        }
        
        //Pesquisa
        ControleAdministracao controleAdm = new ControleAdministracao();
        controleAdm.buscarLivro(txt_isbn.getText());
        
        //Não encontrado
        if(controleAdm.L_titulo.equals(""))
            return;
        
        txt_isbn.setEnabled(false);
        txt_titulo.setText(controleAdm.L_titulo);
        for(int i = 1;i < cmb_autor.getModel().getSize();i++)
            if(((Autor)cmb_autor.getModel().getElementAt(i)).toString().equals(controleAdm.L_Autor.toString()))
                cmb_autor.setSelectedIndex(i);
        for(int i = 1;i < cmb_editora.getModel().getSize();i++)
            if(((Editora)cmb_editora.getModel().getElementAt(i)).toString().equals(controleAdm.L_Editora.toString()))
                cmb_editora.setSelectedIndex(i);
        cmb_ano.setSelectedItem(String.valueOf(controleAdm.L_anoPublicacao));
        cmb_categoria.setSelectedItem(controleAdm.L_categoria);
        txt_resumo.setText(controleAdm.L_resumo);
        txt_sumario.setText(controleAdm.L_sumario);
        txt_qtd.setText(String.valueOf(controleAdm.L_qtdEstoque));
        txt_precoCusto.setText(String.valueOf(controleAdm.L_precoCusto));
        txt_precoVenda.setText(String.valueOf(controleAdm.L_precoVenda));
        txt_precoOferta.setText(String.valueOf(controleAdm.L_precoOferta));
        txt_numPaginas.setText(String.valueOf(controleAdm.L_numPaginas));
        cmb_formato.setSelectedItem(controleAdm.L_formato);
        txt_margemLucro.setText(controleAdm.L_margemLucro);
        rdo_digitalNao.setSelected(controleAdm.L_digital);
        rdo_ofertaNao.setSelected(controleAdm.L_oferta);
        liberaBotao();
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        //Verifica o campo ISBN
        if ( "".equals(txt_isbn.getText()) ) {
            JOptionPane.showMessageDialog(rootPane, "Informe o ISBN para excluir.");
            txt_isbn.requestFocus();
            return;
        }
        
        //Certifica ação, retornando caso cancele
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o livro?") != JOptionPane.YES_OPTION) {
            return;
        }
        //Exclui
        ControleAdministracao adm = new ControleAdministracao();
        adm.removerLivro(txt_isbn.getText());
        txt_isbn.setEditable(true);
        JOptionPane.showMessageDialog(null,"O livro foi excluído com sucesso.");
        limparCampos();        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        //Verifica os campos
        if ("".equals(txt_isbn.getText()) || "".equals(txt_titulo.getText()) || cmb_autor.getSelectedIndex() == 0 ||
                cmb_editora.getSelectedIndex() == 0 || "Selecione..".equals(cmb_categoria.getSelectedItem().toString()) ||
                "".equals(txt_resumo.getText()) || "".equals(txt_sumario.getText()) || "".equals(txt_qtd.getText()) ) {
            JOptionPane.showMessageDialog(null, "Há campos não preenchidos.");
            return;
        }
        
        //Altera
        ControleAdministracao adm = new ControleAdministracao();
        String data = "01" + "01" + cmb_ano.getSelectedItem().toString();
        adm.alterarLivro(txt_isbn.getText(), txt_titulo.getText(), ((Autor)cmb_autor.getSelectedItem()).getID(), ((Editora)cmb_editora.getSelectedItem()).getID(), data, cmb_categoria.getSelectedItem().toString(), txt_resumo.getText(), txt_sumario.getText(),  cmb_formato.getSelectedItem().toString(), txt_numPaginas.getText(), txt_qtd.getText(), txt_precoVenda.getText(), txt_precoOferta.getText(), txt_numPaginas.getText(), oferta, digital);
        JOptionPane.showMessageDialog(null, "O livro foi alterado com sucesso.");
        txt_isbn.setEditable(true);
        limparCampos();
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void txt_precoCustoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precoCustoKeyTyped
        if(!txt_precoCusto.getText().equals("") && !txt_precoVenda.getText().equals("")) {
            try {
                float p_custo = Float.parseFloat(txt_precoCusto.getText());
                float p_venda = Float.parseFloat(txt_precoVenda.getText());
                txt_margemLucro.setText(String.valueOf((((p_venda-p_custo)/p_venda)*100.0f)));
            } catch(NumberFormatException | ArithmeticException ex) {
                txt_margemLucro.setText("#INVÁLIDO");
            }
        } else {
            txt_margemLucro.setText("");
        }
    }//GEN-LAST:event_txt_precoCustoKeyTyped

    private void txt_precoVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precoVendaKeyTyped
        if(!txt_precoCusto.getText().equals("") && !txt_precoVenda.getText().equals("")) {
            try {
                float p_custo = Float.parseFloat(txt_precoCusto.getText());
                float p_venda = Float.parseFloat(txt_precoVenda.getText());
                txt_margemLucro.setText(String.valueOf((((p_venda-p_custo)/p_venda)*100.0f)));
            } catch(NumberFormatException | ArithmeticException ex) {
                txt_margemLucro.setText("#INVÁLIDO");
            }
        } else {
            txt_margemLucro.setText("");
        }
    }//GEN-LAST:event_txt_precoVendaKeyTyped
    
    public void limparCampos() {
        txt_isbn.setText("");
        txt_titulo.setText("");
        cmb_autor.setSelectedIndex(0);
        cmb_editora.setSelectedIndex(0);
        cmb_ano.setSelectedItem("1950");
        cmb_categoria.setSelectedItem("Selecione..");
        txt_resumo.setText("");
        txt_sumario.setText("");
        txt_qtd.setText("");
        txt_precoCusto.setText("");
        txt_precoVenda.setText("");
        txt_precoOferta.setText("");
        txt_numPaginas.setText("");
        txt_margemLucro.setText("");
        cmb_formato.setSelectedItem("Selecione..");
        oferta = false;
        digital = false;
        rdo_digitalNao.setSelected(false);
        rdo_ofertaNao.setSelected(false);
        
        txt_isbn.setEnabled(true);
        bloqueiaBotao();
    }

    public void liberaBotao() {
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
    }

    public void bloqueiaBotao() {
        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb_ano;
    private javax.swing.JComboBox cmb_autor;
    private javax.swing.JComboBox<String> cmb_categoria;
    private javax.swing.JComboBox cmb_editora;
    private javax.swing.JComboBox<String> cmb_formato;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_digitalNao;
    private javax.swing.JRadioButton rdo_digitalSim;
    private javax.swing.JRadioButton rdo_ofertSim;
    private javax.swing.JRadioButton rdo_ofertaNao;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_margemLucro;
    private javax.swing.JTextField txt_numPaginas;
    private javax.swing.JTextField txt_precoCusto;
    private javax.swing.JTextField txt_precoOferta;
    private javax.swing.JTextField txt_precoVenda;
    private javax.swing.JFormattedTextField txt_qtd;
    private javax.swing.JTextArea txt_resumo;
    private javax.swing.JTextArea txt_sumario;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
