/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newstime.fronteira;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import newstime.controle.ControleCarrinho;
import newstime.entidade.Carrinho;
import newstime.entidade.ItemPedido;

/**
 *
 * @author lukin
 */
public class CarrinhoCompras extends javax.swing.JFrame {
    
    private final ControleCarrinho conCar = new ControleCarrinho();
    private ItemPedido escolhido = null;
    
    public CarrinhoCompras() {
        initComponents();
        this.setTitle("Livraria Newstime");
        preencherTabela();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_itens = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbl_preco = new javax.swing.JLabel();
        btn_remover = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();
        btn_continuar = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_mais = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        lbl_sifra = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jLabel1.setText("Meu Carrinho");

        tb_itens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_itensMouseClicked(evt);
            }
        });
        tb_itens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_itensKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_itens);

        jLabel2.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        jLabel2.setText("Subtotal : ");

        lbl_preco.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        lbl_preco.setText("120,00");

        btn_remover.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btn_remover.setText("Remover item selecionado");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        btn_adicionar.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btn_adicionar.setText("Adicionar mais Livros");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        btn_continuar.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btn_continuar.setText("Continuar");
        btn_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarActionPerformed(evt);
            }
        });

        btn_menos.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btn_menos.setText("-");
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_mais.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btn_mais.setText("+");
        btn_mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maisActionPerformed(evt);
            }
        });

        btn_limpar.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btn_limpar.setText("Limpar carrinho");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        lbl_sifra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_sifra.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_limpar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_sifra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_preco)))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_remover)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_mais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_continuar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_adicionar, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mais)
                    .addComponent(btn_menos)
                    .addComponent(btn_adicionar)
                    .addComponent(lbl_sifra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_remover)
                    .addComponent(btn_continuar)
                    .addComponent(btn_limpar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        if(escolhido != null) {
            conCar.retirarItem(escolhido.getLivro().getIsbn());
            preencherTabela();
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void btn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarActionPerformed
        ResumoPedido resumo = ResumoPedido.getInstance();
        resumo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_continuarActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        if(escolhido != null) {
            int quantidade = escolhido.getQuantidade() - 1;
            conCar.alterarItem(escolhido.getLivro().getIsbn(), String.valueOf(quantidade));
            preencherTabela();
        }
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maisActionPerformed
        if(escolhido != null) {
            int quantidade = escolhido.getQuantidade() + 1;
            conCar.alterarItem(escolhido.getLivro().getIsbn(), String.valueOf(quantidade));
            preencherTabela();
        }
    }//GEN-LAST:event_btn_maisActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        conCar.limparCarrinho();
        preencherTabela();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void tb_itensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_itensMouseClicked
        int linha;
        if (evt.getClickCount() == 1) {
            linha = tb_itens.getSelectedRow();
            escolhido = Carrinho.getItens().get(linha);
            System.out.println(escolhido.getLivro().getTitulo());
        }
    }//GEN-LAST:event_tb_itensMouseClicked

    private void tb_itensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_itensKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_itensKeyPressed

    @SuppressWarnings("UseOfObsoleteCollectionType")
    public void preencherTabela() {
        NumberFormat formato_grana = new DecimalFormat ("#,##0.00", new DecimalFormatSymbols (new Locale ("pt", "BR")));
        
        //Cabeçalho
        Vector cabecalho = new Vector();
        cabecalho.add("Item");
        cabecalho.add("Preço");
        cabecalho.add("Quantidade");
        cabecalho.add("Subtotal parcial");
        
        //Itens
        Vector dados = new Vector();
        Vector item;
        float subtotal = 0f;

        for (ItemPedido ix : Carrinho.getItens()) {
            item = new Vector();
            item.add(ix.getLivro().getTitulo());
            item.add(formato_grana.format(ix.getSubtotal()/ix.getQuantidade())); //Divide subtotal por quantidade
            item.add(ix.getQuantidade());
            item.add(formato_grana.format(ix.getSubtotal()));
            subtotal += ix.getSubtotal(); //Soma subtotal para exibir
            dados.add(item);
        }
        
        DefaultTableModel modeloTabela = new DefaultTableModel();
        modeloTabela.setDataVector(dados, cabecalho);
        tb_itens.setModel(modeloTabela);

        //muda tamanho das colunas
        tb_itens.getColumnModel().getColumn(0).setMaxWidth(450);
        tb_itens.getColumnModel().getColumn(1).setMaxWidth(60);
        tb_itens.getColumnModel().getColumn(2).setMaxWidth(75);
        tb_itens.getColumnModel().getColumn(3).setMaxWidth(120);
        
        //Vê o preço subtotal
        lbl_preco.setText(formato_grana.format(subtotal));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_continuar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_mais;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_remover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_sifra;
    private javax.swing.JTable tb_itens;
    // End of variables declaration//GEN-END:variables
}
