/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newstime.fronteira;

/**
 *
 * @author Nátali-Letícia
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nossas_lojas_home = new javax.swing.JLabel();
        televendas = new javax.swing.JLabel();
        atendimento_home = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        button_ok_home = new javax.swing.JButton();
        combo_filtro_home = new javax.swing.JComboBox<String>();
        login_home = new javax.swing.JLabel();
        promocoes_home = new javax.swing.JLabel();
        mais_vendidos_home = new javax.swing.JLabel();
        DesktopPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuLivros = new javax.swing.JMenu();
        MenuLivrosLancamento = new javax.swing.JMenuItem();
        MenuLivrosPreVenda = new javax.swing.JMenuItem();
        MenuLivrosMaisVendidos = new javax.swing.JMenuItem();
        MenuLivrosDigitais = new javax.swing.JMenu();
        MenuLivrosDigitaisLancamentos = new javax.swing.JMenuItem();
        MenuLivrosDigitaisPreVenda = new javax.swing.JMenuItem();
        MenuLivrosDigitaisMaisVendidos = new javax.swing.JMenuItem();
        MenuCategoria = new javax.swing.JMenu();
        MenuCategoriaAdministracao = new javax.swing.JMenuItem();
        MenuCategoriaAgropecuaria = new javax.swing.JMenuItem();
        MenuCategoriaAudiobook = new javax.swing.JMenuItem();
        MenuCategoriaAutoajuda = new javax.swing.JMenuItem();
        MenuCategoriaBibliograficos = new javax.swing.JMenuItem();
        MenuCategoriaCientífico = new javax.swing.JMenuItem();
        MenuCategoriaContos = new javax.swing.JMenuItem();
        MenuCategoriaDidatico = new javax.swing.JMenuItem();
        MenuCategoriaFiccao = new javax.swing.JMenuItem();
        MenuCategoriaHorror = new javax.swing.JMenuItem();
        MenuCategoriaInfantojuvenil = new javax.swing.JMenuItem();
        MenuCategoriaInformatica = new javax.swing.JMenuItem();
        MenuCategoriaLiteraturaBR = new javax.swing.JMenuItem();
        MenuCategoriaLiteraturaEstrangeira = new javax.swing.JMenuItem();
        MenuCategoriaMatematica = new javax.swing.JMenuItem();
        MenuCategoriaMedicina = new javax.swing.JMenuItem();
        MenuCategoriaRomance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        nossas_lojas_home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nossas_lojas_home.setText("Nossas Lojas");
        nossas_lojas_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nossas_lojas_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nossas_lojas_homeMouseClicked(evt);
            }
        });

        televendas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        televendas.setText("Televendas (11)2332-3454");
        televendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        atendimento_home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        atendimento_home.setText("Atendimento");
        atendimento_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atendimento_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atendimento_homeMouseClicked(evt);
            }
        });

        button_ok_home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        button_ok_home.setText("OK");

        combo_filtro_home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combo_filtro_home.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Filtro", "Título", "Autor", "Editora", "Categoria", "ISBN" }));
        combo_filtro_home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combo_filtro_homeFocusGained(evt);
            }
        });

        login_home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        login_home.setText("Entre ou cadastre-se");
        login_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_homeMouseClicked(evt);
            }
        });

        promocoes_home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        promocoes_home.setText("Promoções do dia");
        promocoes_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mais_vendidos_home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mais_vendidos_home.setText("Mais vendidos");
        mais_vendidos_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        DesktopPrincipal.setDesktopManager(null);

        javax.swing.GroupLayout DesktopPrincipalLayout = new javax.swing.GroupLayout(DesktopPrincipal);
        DesktopPrincipal.setLayout(DesktopPrincipalLayout);
        DesktopPrincipalLayout.setHorizontalGroup(
            DesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );
        DesktopPrincipalLayout.setVerticalGroup(
            DesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        MenuLivros.setText("Livros");
        MenuLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosActionPerformed(evt);
            }
        });

        MenuLivrosLancamento.setText("Lançamentos");
        MenuLivrosLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosLancamentoActionPerformed(evt);
            }
        });
        MenuLivros.add(MenuLivrosLancamento);

        MenuLivrosPreVenda.setText("Pré-venda");
        MenuLivrosPreVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosPreVendaActionPerformed(evt);
            }
        });
        MenuLivros.add(MenuLivrosPreVenda);

        MenuLivrosMaisVendidos.setText("Mais vendidos");
        MenuLivrosMaisVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosMaisVendidosActionPerformed(evt);
            }
        });
        MenuLivros.add(MenuLivrosMaisVendidos);

        jMenuBar1.add(MenuLivros);

        MenuLivrosDigitais.setText("Livros Digitais");

        MenuLivrosDigitaisLancamentos.setText("Lançamentos");
        MenuLivrosDigitaisLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosDigitaisLancamentosActionPerformed(evt);
            }
        });
        MenuLivrosDigitais.add(MenuLivrosDigitaisLancamentos);

        MenuLivrosDigitaisPreVenda.setText("Pré-venda");
        MenuLivrosDigitaisPreVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosDigitaisPreVendaActionPerformed(evt);
            }
        });
        MenuLivrosDigitais.add(MenuLivrosDigitaisPreVenda);

        MenuLivrosDigitaisMaisVendidos.setText("Mais vendidos");
        MenuLivrosDigitaisMaisVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosDigitaisMaisVendidosActionPerformed(evt);
            }
        });
        MenuLivrosDigitais.add(MenuLivrosDigitaisMaisVendidos);

        jMenuBar1.add(MenuLivrosDigitais);

        MenuCategoria.setText("Categoria");

        MenuCategoriaAdministracao.setText("Administração");
        MenuCategoria.add(MenuCategoriaAdministracao);

        MenuCategoriaAgropecuaria.setText("Agropecuária");
        MenuCategoriaAgropecuaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriaAgropecuariaActionPerformed(evt);
            }
        });
        MenuCategoria.add(MenuCategoriaAgropecuaria);

        MenuCategoriaAudiobook.setText("Audiobook");
        MenuCategoriaAudiobook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriaAudiobookActionPerformed(evt);
            }
        });
        MenuCategoria.add(MenuCategoriaAudiobook);

        MenuCategoriaAutoajuda.setText("Autoajuda");
        MenuCategoriaAutoajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriaAutoajudaActionPerformed(evt);
            }
        });
        MenuCategoria.add(MenuCategoriaAutoajuda);

        MenuCategoriaBibliograficos.setText("Bibliográficos");
        MenuCategoria.add(MenuCategoriaBibliograficos);

        MenuCategoriaCientífico.setText("Científico");
        MenuCategoria.add(MenuCategoriaCientífico);

        MenuCategoriaContos.setText("Contos");
        MenuCategoria.add(MenuCategoriaContos);

        MenuCategoriaDidatico.setText("Didáticos");
        MenuCategoria.add(MenuCategoriaDidatico);

        MenuCategoriaFiccao.setText("Ficção");
        MenuCategoria.add(MenuCategoriaFiccao);

        MenuCategoriaHorror.setText("Horror");
        MenuCategoria.add(MenuCategoriaHorror);

        MenuCategoriaInfantojuvenil.setText("Infantojuvenil");
        MenuCategoriaInfantojuvenil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriaInfantojuvenilActionPerformed(evt);
            }
        });
        MenuCategoria.add(MenuCategoriaInfantojuvenil);

        MenuCategoriaInformatica.setText("Informática");
        MenuCategoria.add(MenuCategoriaInformatica);

        MenuCategoriaLiteraturaBR.setText("Literatura Brasileira");
        MenuCategoria.add(MenuCategoriaLiteraturaBR);

        MenuCategoriaLiteraturaEstrangeira.setText("Literatura Estrangeira");
        MenuCategoria.add(MenuCategoriaLiteraturaEstrangeira);

        MenuCategoriaMatematica.setText("Matemática");
        MenuCategoria.add(MenuCategoriaMatematica);

        MenuCategoriaMedicina.setText("Medicina");
        MenuCategoria.add(MenuCategoriaMedicina);

        MenuCategoriaRomance.setText("Romance");
        MenuCategoria.add(MenuCategoriaRomance);

        jMenuBar1.add(MenuCategoria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesktopPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nossas_lojas_home)
                                .addGap(18, 18, 18)
                                .addComponent(televendas)
                                .addGap(30, 30, 30)
                                .addComponent(atendimento_home)
                                .addGap(24, 24, 24)
                                .addComponent(promocoes_home)
                                .addGap(18, 18, 18)
                                .addComponent(mais_vendidos_home))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_filtro_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_ok_home, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(login_home)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nossas_lojas_home)
                        .addComponent(televendas)
                        .addComponent(atendimento_home))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mais_vendidos_home)
                        .addComponent(promocoes_home)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ok_home)
                    .addComponent(combo_filtro_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_home))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(DesktopPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );

        setBounds(0, 0, 919, 703);
    }// </editor-fold>//GEN-END:initComponents

    private void nossas_lojas_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nossas_lojas_homeMouseClicked
           Lojas LojasForm = new Lojas();
                LojasForm.setLocationRelativeTo(null);
                LojasForm.show();
                    
    }//GEN-LAST:event_nossas_lojas_homeMouseClicked

    private void login_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_homeMouseClicked
        Login loginForm = new Login();
            loginForm.setLocationRelativeTo(null);
            loginForm.show();
    }//GEN-LAST:event_login_homeMouseClicked

    private void combo_filtro_homeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_filtro_homeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_filtro_homeFocusGained

    private void atendimento_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atendimento_homeMouseClicked
        Atendimento atendForm = new Atendimento();
            atendForm.setLocationRelativeTo(null);
            atendForm.show();        
    }//GEN-LAST:event_atendimento_homeMouseClicked

    private void MenuCategoriaAutoajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriaAutoajudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCategoriaAutoajudaActionPerformed

    private void MenuCategoriaInfantojuvenilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriaInfantojuvenilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCategoriaInfantojuvenilActionPerformed

    private void MenuLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosActionPerformed

    }//GEN-LAST:event_MenuLivrosActionPerformed

    private void MenuLivrosLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosLancamentoActionPerformed
        FormInternoLivro obj = new FormInternoLivro();
        DesktopPrincipal.add (obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuLivrosLancamentoActionPerformed

    private void MenuLivrosPreVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosPreVendaActionPerformed
        FormInternoLivro2 obj = new FormInternoLivro2();
        DesktopPrincipal.add (obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuLivrosPreVendaActionPerformed

    private void MenuLivrosMaisVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosMaisVendidosActionPerformed
        FormInternoLivro3 obj = new FormInternoLivro3();
        DesktopPrincipal.add (obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuLivrosMaisVendidosActionPerformed

    private void MenuLivrosDigitaisLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosDigitaisLancamentosActionPerformed
        FormInternoDigital obj = new FormInternoDigital();
        DesktopPrincipal.add (obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuLivrosDigitaisLancamentosActionPerformed

    private void MenuLivrosDigitaisPreVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosDigitaisPreVendaActionPerformed
        FormInternoDigital2 obj = new FormInternoDigital2();
        DesktopPrincipal.add (obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuLivrosDigitaisPreVendaActionPerformed

    private void MenuLivrosDigitaisMaisVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosDigitaisMaisVendidosActionPerformed
        FormInternoDigital3 obj = new FormInternoDigital3();
        DesktopPrincipal.add (obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuLivrosDigitaisMaisVendidosActionPerformed

    private void MenuCategoriaAgropecuariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriaAgropecuariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCategoriaAgropecuariaActionPerformed

    private void MenuCategoriaAudiobookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriaAudiobookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCategoriaAudiobookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane DesktopPrincipal;
    public javax.swing.JMenu MenuCategoria;
    public javax.swing.JMenuItem MenuCategoriaAdministracao;
    public javax.swing.JMenuItem MenuCategoriaAgropecuaria;
    public javax.swing.JMenuItem MenuCategoriaAudiobook;
    public javax.swing.JMenuItem MenuCategoriaAutoajuda;
    public javax.swing.JMenuItem MenuCategoriaBibliograficos;
    public javax.swing.JMenuItem MenuCategoriaCientífico;
    public javax.swing.JMenuItem MenuCategoriaContos;
    public javax.swing.JMenuItem MenuCategoriaDidatico;
    public javax.swing.JMenuItem MenuCategoriaFiccao;
    public javax.swing.JMenuItem MenuCategoriaHorror;
    public javax.swing.JMenuItem MenuCategoriaInfantojuvenil;
    public javax.swing.JMenuItem MenuCategoriaInformatica;
    public javax.swing.JMenuItem MenuCategoriaLiteraturaBR;
    public javax.swing.JMenuItem MenuCategoriaLiteraturaEstrangeira;
    public javax.swing.JMenuItem MenuCategoriaMatematica;
    public javax.swing.JMenuItem MenuCategoriaMedicina;
    public javax.swing.JMenuItem MenuCategoriaRomance;
    public javax.swing.JMenu MenuLivros;
    public javax.swing.JMenu MenuLivrosDigitais;
    public javax.swing.JMenuItem MenuLivrosDigitaisLancamentos;
    public javax.swing.JMenuItem MenuLivrosDigitaisMaisVendidos;
    public javax.swing.JMenuItem MenuLivrosDigitaisPreVenda;
    public javax.swing.JMenuItem MenuLivrosLancamento;
    public javax.swing.JMenuItem MenuLivrosMaisVendidos;
    public javax.swing.JMenuItem MenuLivrosPreVenda;
    public javax.swing.JLabel atendimento_home;
    public javax.swing.JButton button_ok_home;
    public javax.swing.JComboBox<String> combo_filtro_home;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel login_home;
    public javax.swing.JLabel mais_vendidos_home;
    public javax.swing.JLabel nossas_lojas_home;
    public javax.swing.JLabel promocoes_home;
    public javax.swing.JLabel televendas;
    // End of variables declaration//GEN-END:variables
}
