package newstime.fronteira;

import java.awt.GridLayout;
import java.beans.PropertyVetoException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import newstime.controle.ControleBusca;
import newstime.entidade.BuscaLivro;
import newstime.entidade.Conta;
import newstime.entidade.ContaRestrita;
import newstime.entidade.Livro;
import newstime.excecao.BancoException;

public class Home extends javax.swing.JFrame {
    
    private AcessoAdm acesso;
    private CadastroLivro formLivro;
    private CadastroAutor formAutor;
    private CadastroEditora formEditora;
    private TabelaVendas tabVendas;
    
    private Lojas lojas;
    private Login login;
    private CadastroUsuario cadastroUsu;
    private CarrinhoCompras carrinho;
    private MeusPedidos pedido;
    
    
    /**
     * Creates new form NovoJFrame
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painelPai = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<String>();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPesquisar = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenu();
        itemCat1 = new javax.swing.JMenuItem();
        itemCat2 = new javax.swing.JMenuItem();
        itemCat3 = new javax.swing.JMenuItem();
        itemCat4 = new javax.swing.JMenuItem();
        itemCat5 = new javax.swing.JMenuItem();
        itemCat6 = new javax.swing.JMenuItem();
        itemCat7 = new javax.swing.JMenuItem();
        itemCat8 = new javax.swing.JMenuItem();
        itemCat9 = new javax.swing.JMenuItem();
        itemCat10 = new javax.swing.JMenuItem();
        itemCat11 = new javax.swing.JMenuItem();
        itemCat12 = new javax.swing.JMenuItem();
        itemCat13 = new javax.swing.JMenuItem();
        itemCat14 = new javax.swing.JMenuItem();
        itemCat15 = new javax.swing.JMenuItem();
        itemCat16 = new javax.swing.JMenuItem();
        itemCat17 = new javax.swing.JMenuItem();
        itemCat18 = new javax.swing.JMenuItem();
        itemCat19 = new javax.swing.JMenuItem();
        itemCat20 = new javax.swing.JMenuItem();
        itemCat21 = new javax.swing.JMenuItem();
        itemCat22 = new javax.swing.JMenuItem();
        itemCat23 = new javax.swing.JMenuItem();
        itemCat24 = new javax.swing.JMenuItem();
        itemCat25 = new javax.swing.JMenuItem();
        itemCat26 = new javax.swing.JMenuItem();
        itemMaisVendidos = new javax.swing.JMenuItem();
        itemPromocao = new javax.swing.JMenuItem();
        itemDigital = new javax.swing.JMenuItem();
        menuConta = new javax.swing.JMenu();
        itemCadastro = new javax.swing.JMenuItem();
        itemLogin = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemCarrinho = new javax.swing.JMenuItem();
        itemPedidos = new javax.swing.JMenuItem();
        menuLojas = new javax.swing.JMenu();
        menuAdmin = new javax.swing.JMenu();
        itemAcesso = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemLivro = new javax.swing.JMenuItem();
        itemEditora = new javax.swing.JMenuItem();
        itemAutor = new javax.swing.JMenuItem();
        itemVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPaiLayout = new javax.swing.GroupLayout(painelPai);
        painelPai.setLayout(painelPaiLayout);
        painelPaiLayout.setHorizontalGroup(
            painelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1189, Short.MAX_VALUE)
        );
        painelPaiLayout.setVerticalGroup(
            painelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelPai);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstime/fronteira/logo.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("PESQUISAR");

        cmbFiltro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Filtro", "Título", "Autor", "Editora", "ISBN" }));

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesquisar.setText("OK");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        menuPesquisar.setText("Pesquisar...");

        menuCategoria.setText("Por Categoria");

        itemCat1.setText("Administração");
        itemCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat1ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat1);

        itemCat2.setText("Agropecuária");
        itemCat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat2ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat2);

        itemCat3.setText("Artes");
        itemCat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat3ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat3);

        itemCat4.setText("Áudiolivro");
        itemCat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat4ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat4);

        itemCat5.setText("Auto-Ajuda");
        itemCat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat5ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat5);

        itemCat6.setText("Ciências Biológicas");
        itemCat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat6ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat6);

        itemCat7.setText("Ciências Exatas");
        itemCat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat7ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat7);

        itemCat8.setText("Ciências Humanas");
        itemCat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat8ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat8);

        itemCat9.setText("Contabilidade");
        itemCat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat9ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat9);

        itemCat10.setText("Idioma");
        itemCat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat10ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat10);

        itemCat11.setText("Dicionário");
        itemCat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat11ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat11);

        itemCat12.setText("Didático");
        itemCat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat12ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat12);

        itemCat13.setText("Direito");
        itemCat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat13ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat13);

        itemCat14.setText("Economia");
        itemCat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat14ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat14);

        itemCat15.setText("Engenharia Tecnológica");
        itemCat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat15ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat15);

        itemCat16.setText("Esporte");
        itemCat16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat16ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat16);

        itemCat17.setText("Gastronomia");
        itemCat17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat17ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat17);

        itemCat18.setText("Geografia Histórica");
        itemCat18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat18ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat18);

        itemCat19.setText("Informática");
        itemCat19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat19ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat19);

        itemCat20.setText("Linguística");
        itemCat20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat20ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat20);

        itemCat21.setText("Literatura Estrangeira");
        itemCat21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat21ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat21);

        itemCat22.setText("Literatura Infantil");
        itemCat22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat22ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat22);

        itemCat23.setText("Literatura Nacional");
        itemCat23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat23ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat23);

        itemCat24.setText("Medicina");
        itemCat24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat24ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat24);

        itemCat25.setText("Religião");
        itemCat25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat25ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat25);

        itemCat26.setText("Turismo");
        itemCat26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCat26ActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCat26);

        menuPesquisar.add(menuCategoria);

        itemMaisVendidos.setText("Livros Mais Vendidos");
        itemMaisVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMaisVendidosActionPerformed(evt);
            }
        });
        menuPesquisar.add(itemMaisVendidos);

        itemPromocao.setText("Promoções");
        itemPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPromocaoActionPerformed(evt);
            }
        });
        menuPesquisar.add(itemPromocao);

        itemDigital.setText("Livros Digitais");
        itemDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDigitalActionPerformed(evt);
            }
        });
        menuPesquisar.add(itemDigital);

        jMenuBar1.add(menuPesquisar);

        menuConta.setText("Conta");

        itemCadastro.setText("Cadastre-se");
        itemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroActionPerformed(evt);
            }
        });
        menuConta.add(itemCadastro);

        itemLogin.setText("Login");
        itemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginActionPerformed(evt);
            }
        });
        menuConta.add(itemLogin);

        itemLogout.setText("Logout");
        itemLogout.setEnabled(false);
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        menuConta.add(itemLogout);
        menuConta.add(jSeparator1);

        itemCarrinho.setText("Meu Carrinho");
        itemCarrinho.setEnabled(false);
        itemCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCarrinhoActionPerformed(evt);
            }
        });
        menuConta.add(itemCarrinho);

        itemPedidos.setText("Meus Pedidos");
        itemPedidos.setEnabled(false);
        itemPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPedidosActionPerformed(evt);
            }
        });
        menuConta.add(itemPedidos);

        jMenuBar1.add(menuConta);

        menuLojas.setText("Lojas");
        menuLojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLojasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuLojas);

        menuAdmin.setText("Gerencial");

        itemAcesso.setText("Acesso restrito");
        itemAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcessoActionPerformed(evt);
            }
        });
        menuAdmin.add(itemAcesso);

        itemSair.setText("Sair");
        itemSair.setEnabled(false);
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuAdmin.add(itemSair);
        menuAdmin.add(jSeparator2);

        itemLivro.setText("Livros");
        itemLivro.setEnabled(false);
        itemLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLivroActionPerformed(evt);
            }
        });
        menuAdmin.add(itemLivro);

        itemEditora.setText("Editoras");
        itemEditora.setEnabled(false);
        itemEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditoraActionPerformed(evt);
            }
        });
        menuAdmin.add(itemEditora);

        itemAutor.setText("Autores");
        itemAutor.setEnabled(false);
        itemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutorActionPerformed(evt);
            }
        });
        menuAdmin.add(itemAutor);

        itemVenda.setText("Pedidos/Vendas");
        itemVenda.setEnabled(false);
        itemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVendaActionPerformed(evt);
            }
        });
        menuAdmin.add(itemVenda);

        jMenuBar1.add(menuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar)))
                        .addGap(0, 380, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        //Valida
        if(!validarCampos()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            return;
        }
        
        ControleBusca controleBusca = new ControleBusca();
        ArrayList<Livro> resultBusca;
        NumberFormat formato_grana = new DecimalFormat ("#,##0.00", new DecimalFormatSymbols (new Locale ("pt", "BR")));
        
        painelPai.removeAll();
        GridLayout gerente = new GridLayout(15, 1);//Mostra até 15 itens um em baixo do outro
        painelPai.setLayout(gerente);

        try {
            switch(cmbFiltro.getSelectedIndex()) {
                case 1: //Título
                    controleBusca.fazerBusca(txtPesquisa.getText(), 2);
                    break;
                case 2: //Autor
                    controleBusca.fazerBusca(txtPesquisa.getText(), 3);
                    break;
                case 3: //Editora
                    controleBusca.fazerBusca(txtPesquisa.getText(), 1);
                    break;
                case 4: //ISBN
                    controleBusca.fazerBusca(txtPesquisa.getText(), 4);
                    break;
                default:
                    return;
            }
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        
        resultBusca = controleBusca.getResultadosBusca();
        
        for (Livro ver : resultBusca) {
            PainelBusca p1 = new PainelBusca();
            painelPai.add(p1);
            p1.getTxt_titulo().setText(ver.getTitulo());
            p1.getTxt_autor().setText(ver.getAutor().getNome());
            p1.getTxt_preco().setText(formato_grana.format(ver.getPrecoVenda()));
            p1.setLi(ver);
        }
        
        corrigirBug();//Corrige
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void itemCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat1ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.ADMINISTRACAO);
    }//GEN-LAST:event_itemCat1ActionPerformed

    private void itemCat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat2ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.AGROPECUARIA);
    }//GEN-LAST:event_itemCat2ActionPerformed

    private void itemCat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat3ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.ARTES);
    }//GEN-LAST:event_itemCat3ActionPerformed

    private void itemCat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat4ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.AUDIOLIVRO);
    }//GEN-LAST:event_itemCat4ActionPerformed

    private void itemCat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat5ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.AUTOAJUDA);
    }//GEN-LAST:event_itemCat5ActionPerformed

    private void itemCat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat6ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.CIENCIAS_BIO);
    }//GEN-LAST:event_itemCat6ActionPerformed

    private void itemCat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat7ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.CIENCIAS_EXA);
    }//GEN-LAST:event_itemCat7ActionPerformed

    private void itemCat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat8ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.CIENCIAS_HUM);
    }//GEN-LAST:event_itemCat8ActionPerformed

    private void itemCat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat9ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.CONTABILIDADE);
    }//GEN-LAST:event_itemCat9ActionPerformed

    private void itemCat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat10ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.IDIOMA);
    }//GEN-LAST:event_itemCat10ActionPerformed

    private void itemCat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat11ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.DICIONARIO);
    }//GEN-LAST:event_itemCat11ActionPerformed

    private void itemCat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat12ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.DIDATICO);
    }//GEN-LAST:event_itemCat12ActionPerformed

    private void itemCat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat13ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.DIREITO);
    }//GEN-LAST:event_itemCat13ActionPerformed

    private void itemCat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat14ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.ECONOMIA);
    }//GEN-LAST:event_itemCat14ActionPerformed

    private void itemCat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat15ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.ENG_TEC);
    }//GEN-LAST:event_itemCat15ActionPerformed

    private void itemCat16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat16ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.ESPORTE);
    }//GEN-LAST:event_itemCat16ActionPerformed

    private void itemCat17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat17ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.GASTRONOMIA);
    }//GEN-LAST:event_itemCat17ActionPerformed

    private void itemCat18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat18ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.GEO_HIST);
    }//GEN-LAST:event_itemCat18ActionPerformed

    private void itemCat19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat19ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.INFORMATICA);
    }//GEN-LAST:event_itemCat19ActionPerformed

    private void itemCat20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat20ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.LINGUISTICA);
    }//GEN-LAST:event_itemCat20ActionPerformed

    private void itemCat21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat21ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.LITER_ESTR);
    }//GEN-LAST:event_itemCat21ActionPerformed

    private void itemCat22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat22ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.LITER_INFA);
    }//GEN-LAST:event_itemCat22ActionPerformed

    private void itemCat23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat23ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.LITER_NACIO);
    }//GEN-LAST:event_itemCat23ActionPerformed

    private void itemCat24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat24ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.MEDICINA);
    }//GEN-LAST:event_itemCat24ActionPerformed

    private void itemCat25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat25ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.RELIGIAO);
    }//GEN-LAST:event_itemCat25ActionPerformed

    private void itemCat26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCat26ActionPerformed
        this.buscarCategoria(Livro.CategoriaLivro.TURISMO);
    }//GEN-LAST:event_itemCat26ActionPerformed

    private void itemMaisVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMaisVendidosActionPerformed
        ArrayList<Livro> resultBusca;
        BuscaLivro busca = new BuscaLivro();
        NumberFormat formato_grana = new DecimalFormat ("#,##0.00", new DecimalFormatSymbols (new Locale ("pt", "BR")));
        
        painelPai.removeAll();
        GridLayout gerente = new GridLayout(15, 1);//Mostra até 15 itens um em baixo do outro
        painelPai.setLayout(gerente);
        
        try {
            resultBusca = busca.buscarMaisVendidos();
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        
        for (Livro ver : resultBusca) {
            PainelBusca p1 = new PainelBusca();
            painelPai.add(p1);
            p1.getTxt_titulo().setText(ver.getTitulo());
            p1.getTxt_autor().setText(ver.getAutor().getNome());
            p1.getTxt_preco().setText(formato_grana.format(ver.getPrecoVenda()));
            p1.setLi(ver);
        }
        
        corrigirBug();//Corrige
    }//GEN-LAST:event_itemMaisVendidosActionPerformed

    private void itemPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPromocaoActionPerformed
        ArrayList<Livro> resultBusca;
        BuscaLivro busca = new BuscaLivro();
        NumberFormat formato_grana = new DecimalFormat ("#,##0.00", new DecimalFormatSymbols (new Locale ("pt", "BR")));
        
        painelPai.removeAll();
        GridLayout gerente = new GridLayout(15, 1);//Mostra até 15 itens um em baixo do outro
        painelPai.setLayout(gerente);
        
        try {
            resultBusca = busca.buscarOfertas();
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        
        for (Livro ver : resultBusca) {
            PainelBusca p1 = new PainelBusca();
            painelPai.add(p1);
            p1.getTxt_titulo().setText(ver.getTitulo());
            p1.getTxt_autor().setText(ver.getAutor().getNome());
            p1.getTxt_preco().setText(formato_grana.format(ver.getPrecoVenda()));
            p1.setLi(ver);
        }
        
        corrigirBug();//Corrige
    }//GEN-LAST:event_itemPromocaoActionPerformed

    private void itemDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDigitalActionPerformed
        ArrayList<Livro> resultBusca;
        BuscaLivro busca = new BuscaLivro();
        NumberFormat formato_grana = new DecimalFormat ("#,##0.00", new DecimalFormatSymbols (new Locale ("pt", "BR")));
        
        painelPai.removeAll();
        GridLayout gerente = new GridLayout(15, 1);//Mostra até 15 itens um em baixo do outro
        painelPai.setLayout(gerente);
        
        try {
            resultBusca = busca.buscarDigitais();
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        
        for (Livro ver : resultBusca) {
            PainelBusca p1 = new PainelBusca();
            painelPai.add(p1);
            p1.getTxt_titulo().setText(ver.getTitulo());
            p1.getTxt_autor().setText(ver.getAutor().getNome());
            p1.getTxt_preco().setText(formato_grana.format(ver.getPrecoVenda()));
            p1.setLi(ver);
        }
        
        corrigirBug();//Corrige
    }//GEN-LAST:event_itemDigitalActionPerformed

    private void itemAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcessoActionPerformed
        acesso = new AcessoAdm();
        acesso.setVisible(true);
    }//GEN-LAST:event_itemAcessoActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        ContaRestrita.deslogar();
        //DESABILITA ADMIN
        Home.itemAcesso.setEnabled(true);
        
        Home.itemSair.setEnabled(false);
        Home.itemLivro.setEnabled(false);
        Home.itemEditora.setEnabled(false);
        Home.itemAutor.setEnabled(false);
        Home.itemVenda.setEnabled(false);
    }//GEN-LAST:event_itemSairActionPerformed

    private void menuLojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLojasActionPerformed
        lojas = Lojas.getInstance();
        lojas.setVisible(true);
    }//GEN-LAST:event_menuLojasActionPerformed

    private void itemLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLivroActionPerformed
        CadastroLivro cl = new CadastroLivro();
        cl.setVisible(true);
    }//GEN-LAST:event_itemLivroActionPerformed

    private void itemEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditoraActionPerformed
        CadastroEditora ca = new CadastroEditora();
        ca.setVisible(true);
    }//GEN-LAST:event_itemEditoraActionPerformed

    private void itemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutorActionPerformed
        CadastroAutor ca = new CadastroAutor();
        ca.setVisible(true);
    }//GEN-LAST:event_itemAutorActionPerformed

    private void itemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVendaActionPerformed
        tabVendas = TabelaVendas.getInstance();
        tabVendas.setVisible(false);
    }//GEN-LAST:event_itemVendaActionPerformed

    private void itemCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCarrinhoActionPerformed
        carrinho = new CarrinhoCompras();
        carrinho.setVisible(true);
    }//GEN-LAST:event_itemCarrinhoActionPerformed

    private void itemPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPedidosActionPerformed
        pedido = MeusPedidos.getInstance();
        pedido.setVisible(true);
    }//GEN-LAST:event_itemPedidosActionPerformed

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        Conta.deslogar();
        //DESABILITA CLIENTE
        Home.itemCadastro.setEnabled(true);
        Home.itemLogin.setEnabled(true);

        Home.itemLogout.setEnabled(false);
        Home.itemLivro.setEnabled(false);
        Home.itemCarrinho.setEnabled(false);
        Home.itemPedidos.setEnabled(false);
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void itemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroActionPerformed
        cadastroUsu = CadastroUsuario.getInstance();
        cadastroUsu.setVisible(true);
    }//GEN-LAST:event_itemCadastroActionPerformed

    private void itemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginActionPerformed
        login = Login.getInstance(this);
        login.setVisible(true);
    }//GEN-LAST:event_itemLoginActionPerformed
    
    private void buscarCategoria(Livro.CategoriaLivro categoria) {
        ControleBusca controleBusca = new ControleBusca();
        ArrayList<Livro> resultBusca;
        NumberFormat formato_grana = new DecimalFormat ("#,##0.00", new DecimalFormatSymbols (new Locale ("pt", "BR")));
        
        painelPai.removeAll();
        GridLayout gerente = new GridLayout(15, 1);//Mostra até 15 itens um em baixo do outro
        painelPai.setLayout(gerente);
        
        try {
            controleBusca.fazerBusca(categoria.toString(), 5);
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        
        resultBusca = controleBusca.getResultadosBusca();
        
        for (Livro ver : resultBusca) {
            PainelBusca p1 = new PainelBusca();
            painelPai.add(p1);
            p1.getTxt_titulo().setText(ver.getTitulo());
            p1.getTxt_autor().setText(ver.getAutor().getNome());
            p1.getTxt_preco().setText(formato_grana.format(ver.getPrecoVenda()));
            p1.setLi(ver);
        }
        
        corrigirBug();//Corrige
    }
    
    
    private void setMaximized(JInternalFrame form) {
        try {
            form.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean validarCampos() {
        return (!(txtPesquisa.getText().equals("") || cmbFiltro.getSelectedIndex() == 0));
    }
    
    private void limparCampos() {
        txtPesquisa.setText("");
    }
    
    private void corrigirBug(){
        int x = this.getHeight();
        int y = this.getWidth();
        this.setSize(y - 1, x - 1);
        this.setSize(y, x);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Metal (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnPesquisar;
    public javax.swing.JComboBox<String> cmbFiltro;
    public static javax.swing.JMenuItem itemAcesso;
    public static javax.swing.JMenuItem itemAutor;
    public static javax.swing.JMenuItem itemCadastro;
    public static javax.swing.JMenuItem itemCarrinho;
    public static javax.swing.JMenuItem itemCat1;
    public static javax.swing.JMenuItem itemCat10;
    public static javax.swing.JMenuItem itemCat11;
    public static javax.swing.JMenuItem itemCat12;
    public static javax.swing.JMenuItem itemCat13;
    public static javax.swing.JMenuItem itemCat14;
    public static javax.swing.JMenuItem itemCat15;
    public static javax.swing.JMenuItem itemCat16;
    public static javax.swing.JMenuItem itemCat17;
    public static javax.swing.JMenuItem itemCat18;
    public static javax.swing.JMenuItem itemCat19;
    public static javax.swing.JMenuItem itemCat2;
    public static javax.swing.JMenuItem itemCat20;
    public static javax.swing.JMenuItem itemCat21;
    public static javax.swing.JMenuItem itemCat22;
    public static javax.swing.JMenuItem itemCat23;
    public static javax.swing.JMenuItem itemCat24;
    public static javax.swing.JMenuItem itemCat25;
    public static javax.swing.JMenuItem itemCat26;
    public static javax.swing.JMenuItem itemCat3;
    public static javax.swing.JMenuItem itemCat4;
    public static javax.swing.JMenuItem itemCat5;
    public static javax.swing.JMenuItem itemCat6;
    public static javax.swing.JMenuItem itemCat7;
    public static javax.swing.JMenuItem itemCat8;
    public static javax.swing.JMenuItem itemCat9;
    public static javax.swing.JMenuItem itemDigital;
    public static javax.swing.JMenuItem itemEditora;
    public static javax.swing.JMenuItem itemLivro;
    public static javax.swing.JMenuItem itemLogin;
    public static javax.swing.JMenuItem itemLogout;
    public static javax.swing.JMenuItem itemMaisVendidos;
    public static javax.swing.JMenuItem itemPedidos;
    public static javax.swing.JMenuItem itemPromocao;
    public static javax.swing.JMenuItem itemSair;
    public static javax.swing.JMenuItem itemVenda;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JPopupMenu.Separator jSeparator2;
    public static javax.swing.JMenu menuAdmin;
    public static javax.swing.JMenu menuCategoria;
    public static javax.swing.JMenu menuConta;
    public static javax.swing.JMenu menuLojas;
    public static javax.swing.JMenu menuPesquisar;
    public static javax.swing.JPanel painelPai;
    public static javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
