package newstime.fronteira;

import javax.swing.JOptionPane;
import newstime.controle.ControleContaCliente;
import newstime.entidade.Cliente;
import newstime.entidade.Conta;
import newstime.excecao.BancoException;
import newstime.excecao.FormatacaoIncorretaException;
import newstime.excecao.NegocioException;

public class Login extends javax.swing.JFrame {

    private static Login janela = null;
    private static Home h = null;
    private ControleContaCliente conCliente;
    
    private Login (Home home) {
        initComponents();
        Login.h = home;
    }
    
    public static Login getInstance(Home home) {
        if(janela == null)
            janela = new Login(home);
        return janela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblCadstro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Identificação");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("E-mail:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Senha:");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblCadstro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCadstro.setText("Não possui cadastro?");
        lblCadstro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadstro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadstroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSenha)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEntrar)
                                        .addGap(33, 33, 33)
                                        .addComponent(lblCadstro))
                                    .addComponent(jLabel3))
                                .addGap(0, 131, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(lblCadstro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(!validarCampos()) {
            JOptionPane.showMessageDialog(null,"Preencha todos os campos.");
            return;
        }
        
        String email = txtEmail.getText();
        String senha = txtSenha.getText();
        
        try {
            Cliente c = new Cliente();
            c.setEmail(email);
            c.setSenha(senha);
            Conta.logar(c);
            
            JOptionPane.showMessageDialog(null,"Seja bem-vindo(a), "+Conta.getCliente().getNome()+".");
            limparCampos();
            
            //HABILITA CLIENTE
            Home.itemCadastro.setEnabled(false);
            Home.itemLogin.setEnabled(false);

            Home.itemLogout.setEnabled(true);
            Home.itemLivro.setEnabled(true);
            Home.itemCarrinho.setEnabled(true);
            Home.itemPedidos.setEnabled(true);

            this.setVisible(false);
        } catch (BancoException | NegocioException | FormatacaoIncorretaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblCadstroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadstroMouseClicked
        CadastroUsuario cUsu = CadastroUsuario.getInstance();
        cUsu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCadstroMouseClicked

    private boolean validarCampos() {
        return (!(txtEmail.getText().equals("") || txtSenha.getText().equals("")));
    }
    
    private void limparCampos() {
        txtEmail.setText("");
        txtSenha.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCadstro;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
