/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newstime.fronteira;

import java.text.SimpleDateFormat;
import newstime.entidade.Livro;

/**
 *
 * @author Usuario
 */
public class MaisDetalhes extends javax.swing.JFrame {
    private Livro liv = new Livro();

    public Livro getLiv() {
        return liv;
    }

    public void setLiv(Livro liv) {
        this.liv = liv;
    }
    
    /**
     * Creates new form MaisDetalhes
     */
    public MaisDetalhes() {
        initComponents();
        this.setTitle("Detalhes");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_resumo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_autor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_formato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_editora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_numeroPaginas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_dataPublicacao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_sumario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_isbn = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Resumo");

        txt_resumo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_resumo.setEnabled(false);

        jLabel2.setText("Autor");

        txt_autor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_autor.setEnabled(false);

        jLabel3.setText("Formato");

        txt_formato.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_formato.setEnabled(false);

        jLabel4.setText("Editora");

        txt_editora.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_editora.setEnabled(false);

        jLabel5.setText("Número de paginas");

        txt_numeroPaginas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_numeroPaginas.setEnabled(false);

        jLabel9.setText("Titulo");

        txt_titulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_titulo.setEnabled(false);

        jLabel6.setText("Data publicação");

        txt_dataPublicacao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_dataPublicacao.setEnabled(false);

        jLabel10.setText("Categoria");

        txt_categoria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_categoria.setEnabled(false);

        jLabel16.setText("Sumário");

        txt_sumario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_sumario.setEnabled(false);

        jLabel11.setText("ISBN");

        txt_isbn.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_isbn.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_numeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_editora, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txt_titulo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_dataPublicacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_formato, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_resumo)
                            .addComponent(txt_sumario, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txt_editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dataPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_sumario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_resumo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //pn_Busca bb = new pn_Busca();
        
        //Livro liv = new Livro();
        //liv = bb.getLi();
        
        SimpleDateFormat formaData = new SimpleDateFormat("dd/MM/yyyy");
        String cate = "";
        
        txt_sumario.setText(this.liv.getResumo());
        txt_resumo.setText(this.liv.getSumario());
        txt_autor.setText(this.liv.getAutor().getNome());
        txt_formato.setText(this.liv.getFormato().toString());
        txt_editora.setText(this.liv.getEditora().getNome());
        txt_numeroPaginas.setText(String.valueOf(this.liv.getNumPaginas()));
        txt_dataPublicacao.setText(formaData.format(this.liv.getAnoPublicacao()));
        txt_titulo.setText(this.liv.getTitulo());
        switch(this.liv.getCategoria()) {
            case ADMINISTRACAO:
                cate = "Administração";
                break;
            case AGROPECUARIA:
                cate = "Agropecuária";
                break;
            case ARTES:
                cate = "Artes";
                break;
            case AUDIOLIVRO:
                cate = "Áudiolivro";
                break;
            case AUTOAJUDA:
                cate = "Autoajuda";
                break;
            case CIENCIAS_BIO:
                cate = "Ciências Biológicas";
                break;
            case CIENCIAS_EXA:
                cate = "Ciências Exatas";
                break;
            case CIENCIAS_HUM:
                cate = "Ciências Humanas";
                break;
            case CONTABILIDADE:
                cate = "Contabilidade";
                break;
            case IDIOMA:
                cate = "Idiomas";
                break;
            case DICIONARIO:
                cate = "Dicionário";
                break;
            case DIDATICO:
                cate = "Livro Didático";
                break;
            case DIREITO:
                cate = "Direito";
                break;
            case ECONOMIA:
                cate = "Economia";
                break;
            case ENG_TEC:
                cate = "Engenharia e Tecnologia";
                break;
            case ESPORTE:
                cate = "Esporte";
                break;
            case GASTRONOMIA:
                cate = "Gastronomia";
                break;
            case GEO_HIST:
                cate = "Geografia e História";
                break;
            case INFORMATICA:
                cate = "Informática";
                break;
            case LINGUISTICA:
                cate = "Linguística";
                break;
            case LITER_ESTR:
                cate = "Literatura Estrangeira";
                break;
            case LITER_INFA:
                cate = "Literatura Infantil";
                break;
            case LITER_NACIO:
                cate = "Literatura Nacional";
                break;
            case MEDICINA:
                cate = "Medicina";
                break;
            case RELIGIAO:
                cate = "Religião";
                break;
            case TURISMO:
                cate = "Turismo";
                break;
        }
        txt_categoria.setText(cate);
        txt_isbn.setText(this.liv.getIsbn());
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_dataPublicacao;
    private javax.swing.JTextField txt_editora;
    private javax.swing.JTextField txt_formato;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_numeroPaginas;
    private javax.swing.JTextField txt_resumo;
    private javax.swing.JTextField txt_sumario;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
